channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=23.3.1
- pip:
  - mlflow==2.14.1
  - dspy-ai==2.4.10
  - cloudpickle==3.0.0
  - weaviate-client==4.5.5
  - pydantic~=2.7.0
  - azureml-inference-server-http==1.3.0
name: mlflow-env
